default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  # ---------------------------------------------------------
  # Standard Hooks
  # ---------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]

      - id: end-of-file-fixer
        stages: [pre-commit]

      - id: check-merge-conflict

      - id: check-yaml

      - id: check-toml

      - id: check-added-large-files

  # ---------------------------------------------------------
  # Ruff
  # ---------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/.*\.py$
        stages: [pre-commit]

      - id: ruff-format
        files: ^backend/.*\.py$
        stages: [pre-commit]

  # ---------------------------------------------------------
  # Local Hooks
  # ---------------------------------------------------------
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c "cd backend && uv run --locked mypy app"
        language: system
        pass_filenames: false
        stages: [pre-push]
