"""add_file_size_bytes_to_documents

Revision ID: 23405f43b205
Revises: d706a2f4d94d
Create Date: 2026-09-05 09:21:11.438587

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23405f43b205"
down_revision: str | Sequence[str] | None = "d706a2f4d94d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_size_bytes", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_size_bytes")
    # ### end Alembic commands ###
