"""Add updated_at to documents

Revision ID: 382fcbcec7d8
Revises: 23405f43b205
Create Date: 2026-09-05 21:01:09.443161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "382fcbcec7d8"
down_revision: str | Sequence[str] | None = "23405f43b205"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="1970-01-01 00:00:00",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "updated_at")
    # ### end Alembic commands ###
