"""add_sources_to_chat_messages

Revision ID: d706a2f4d94d
Revises: db51c965f115
Create Date: 2026-09-05 09:17:39.595516

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d706a2f4d94d"
down_revision: str | Sequence[str] | None = "db51c965f115"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("sources", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "sources")
    # ### end Alembic commands ###
