"""add summarized_message_count

Revision ID: db51c965f115
Revises: 099fffd279e9
Create Date: 2026-08-28 23:09:32.686212

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db51c965f115"
down_revision: str | Sequence[str] | None = "099fffd279e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_sessions",
        sa.Column(
            "summarized_message_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "summarized_message_count")
    # ### end Alembic commands ###
